[package]
name = "pretweet"
version = "0.1.0"
authors = ["jamel"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
textgenlib = { path = "./src/textgenlib", version = "0.1.0" }